const withAlpha = (name) =>
    `rgb(var(--${name}) / calc(var(--${name}-alpha, 1) * <alpha-value>))`;

export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                "app-bg": withAlpha("app-bg"),
                "app-bg-soft": withAlpha("app-bg-soft"),
                "app-surface-1": withAlpha("app-surface-1"),
                "app-surface-2": withAlpha("app-surface-2"),
                "app-surface-3": withAlpha("app-surface-3"),
                "app-surface-4": withAlpha("app-surface-4"),
                "app-surface-5": withAlpha("app-surface-5"),
                "app-surface-hover": withAlpha("app-surface-hover"),
                "app-text": withAlpha("app-text"),
                "app-border": withAlpha("app-border"),
                "app-grid": withAlpha("app-grid"),
                "app-ink": withAlpha("app-ink"),
                "app-overlay": withAlpha("app-overlay"),
                "app-overlay-soft": withAlpha("app-overlay-soft"),
                "app-scale": withAlpha("app-scale"),
                "on-accent": withAlpha("on-accent"),
                "on-bright": withAlpha("on-bright"),
                "ink-10": withAlpha("ink-10"),
                "ink-20": withAlpha("ink-20"),
                "ink-50": withAlpha("ink-50"),
                "ink-60": withAlpha("ink-60"),
                "ink-70": withAlpha("ink-70"),
                "ink-80": withAlpha("ink-80"),
                "ink-hover": withAlpha("ink-hover"),
                "glow-4": withAlpha("glow-4"),
                "glow-5": withAlpha("glow-5"),
                "glow-10": withAlpha("glow-10"),
                "glow-50": withAlpha("glow-50"),
                "surface-input": withAlpha("surface-input"),
                "surface-input-strong": withAlpha("surface-input-strong"),
                "surface-input-muted": withAlpha("surface-input-muted"),
                "surface-input-soft": withAlpha("surface-input-soft"),
                "surface-toggle-off": withAlpha("surface-toggle-off"),
                "surface-tone": withAlpha("surface-tone"),
                "surface-modal": withAlpha("surface-modal"),
                "surface-danger": withAlpha("surface-danger"),
                "surface-danger-soft": withAlpha("surface-danger-soft"),
                "surface-warning": withAlpha("surface-warning"),
                "surface-success": withAlpha("surface-success"),
                "surface-rail": withAlpha("surface-rail"),
                "surface-pane": withAlpha("surface-pane"),
                "surface-panel": withAlpha("surface-panel"),
                "surface-panel-strong": withAlpha("surface-panel-strong"),
                "surface-range": withAlpha("surface-range"),
                "surface-popover": withAlpha("surface-popover"),
                "surface-button-muted": withAlpha("surface-button-muted"),
                muted: withAlpha("muted"),
                subtle: withAlpha("subtle"),
                faint: withAlpha("faint"),
                ink: withAlpha("ink"),
                "ink-muted": withAlpha("ink-muted"),
                "danger-soft": withAlpha("danger-soft"),
                "danger-faint": withAlpha("danger-faint"),
                "warning-soft": withAlpha("warning-soft"),
                "success-soft": withAlpha("success-soft"),
                "success-faint": withAlpha("success-faint"),
                "info-soft": withAlpha("info-soft"),
                "indigo-soft": withAlpha("indigo-soft"),
                "purple-soft": withAlpha("purple-soft"),
                "yellow-soft": withAlpha("yellow-soft"),
                "accent-brand": withAlpha("accent-brand"),
                "accent-brand-strong": withAlpha("accent-brand-strong"),
                "accent-brand-soft": withAlpha("accent-brand-soft"),
                "accent-brand-deep": withAlpha("accent-brand-deep"),
                "accent-warning": withAlpha("accent-warning"),
                "accent-warning-strong": withAlpha("accent-warning-strong"),
                "accent-warning-deep": withAlpha("accent-warning-deep"),
                "accent-warning-mid": withAlpha("accent-warning-mid"),
                "accent-warning-border": withAlpha("accent-warning-border"),
                "accent-danger": withAlpha("accent-danger"),
                "accent-danger-soft": withAlpha("accent-danger-soft"),
                "accent-danger-strong": withAlpha("accent-danger-strong"),
                "accent-danger-deep": withAlpha("accent-danger-deep"),
                "accent-danger-muted": withAlpha("accent-danger-muted"),
                "accent-danger-alt-mid": withAlpha("accent-danger-alt-mid"),
                "accent-danger-alt-strong": withAlpha(
                    "accent-danger-alt-strong"
                ),
                "accent-danger-alt-soft": withAlpha("accent-danger-alt-soft"),
                "accent-danger-alt-darker": withAlpha(
                    "accent-danger-alt-darker"
                ),
                "accent-success": withAlpha("accent-success"),
                "accent-success-strong": withAlpha("accent-success-strong"),
                "accent-profit": withAlpha("accent-profit"),
                "accent-profit-strong": withAlpha("accent-profit-strong"),
                "accent-profit-deep": withAlpha("accent-profit-deep"),
                "accent-profit-darker": withAlpha("accent-profit-darker"),
                "accent-info-link": withAlpha("accent-info-link"),
                "accent-highlight": withAlpha("accent-highlight"),
                "gradient-start": withAlpha("gradient-start"),
                "gradient-mid": withAlpha("gradient-mid"),
                "gradient-end": withAlpha("gradient-end"),
                "action-add-bg": withAlpha("action-add-bg"),
                "action-add-border": withAlpha("action-add-border"),
                "action-add-hover": withAlpha("action-add-hover"),
                "action-add-text": withAlpha("action-add-text"),
                "action-close-bg": withAlpha("action-close-bg"),
                "action-close-border": withAlpha("action-close-border"),
                "action-close-hover": withAlpha("action-close-hover"),
                "action-close-text": withAlpha("action-close-text"),
                "action-pause-bg": withAlpha("action-pause-bg"),
                "action-pause-border": withAlpha("action-pause-border"),
                "action-pause-hover": withAlpha("action-pause-hover"),
                "action-pause-text": withAlpha("action-pause-text"),
                "pnl-shell-bg": withAlpha("pnl-shell-bg"),
                "pnl-shell-border": withAlpha("pnl-shell-border"),
                "pnl-track": withAlpha("pnl-track"),
                "pnl-positive-bg": withAlpha("pnl-positive-bg"),
                "pnl-negative-bg": withAlpha("pnl-negative-bg"),
                "pnl-positive-text": withAlpha("pnl-positive-text"),
                "pnl-negative-text": withAlpha("pnl-negative-text"),
                "btn-ghost-bg": withAlpha("btn-ghost-bg"),
                "btn-ghost-hover": withAlpha("btn-ghost-hover"),
                "btn-ghost-border": withAlpha("btn-ghost-border"),
                "btn-ghost-text": withAlpha("btn-ghost-text"),
                "btn-ok-bg": withAlpha("btn-ok-bg"),
                "btn-ok-border": withAlpha("btn-ok-border"),
                "btn-ok-text": withAlpha("btn-ok-text"),
                "btn-ok-hover-bg": withAlpha("btn-ok-hover-bg"),
                "btn-ok-hover-border": withAlpha("btn-ok-hover-border"),
                "btn-ok-hover-text": withAlpha("btn-ok-hover-text"),
                "btn-chip-bg": withAlpha("btn-chip-bg"),
                "btn-chip-border": withAlpha("btn-chip-border"),
                "btn-chip-text": withAlpha("btn-chip-text"),
                "btn-chip-hover": withAlpha("btn-chip-hover"),
                "line-subtle": withAlpha("line-subtle"),
                "line-weak": withAlpha("line-weak"),
                "line-muted": withAlpha("line-muted"),
                "line-strong": withAlpha("line-strong"),
                "line-stronger": withAlpha("line-stronger"),
                "line-solid": withAlpha("line-solid"),
                "line-ink": withAlpha("line-ink"),
                "line-ink-muted": withAlpha("line-ink-muted"),
                "line-ink-strong": withAlpha("line-ink-strong"),
                "line-panel": withAlpha("line-panel"),
                "line-panel-strong": withAlpha("line-panel-strong"),
                "line-panel-soft": withAlpha("line-panel-soft"),
                "indicator-rsi-bg": withAlpha("indicator-rsi-bg"),
                "indicator-rsi-text": withAlpha("indicator-rsi-text"),
                "indicator-sma-on-rsi-bg": withAlpha("indicator-sma-on-rsi-bg"),
                "indicator-sma-on-rsi-text": withAlpha(
                    "indicator-sma-on-rsi-text"
                ),
                "indicator-stoch-rsi-bg": withAlpha("indicator-stoch-rsi-bg"),
                "indicator-stoch-rsi-text": withAlpha(
                    "indicator-stoch-rsi-text"
                ),
                "indicator-adx-bg": withAlpha("indicator-adx-bg"),
                "indicator-adx-text": withAlpha("indicator-adx-text"),
                "indicator-atr-bg": withAlpha("indicator-atr-bg"),
                "indicator-atr-text": withAlpha("indicator-atr-text"),
                "indicator-ema-bg": withAlpha("indicator-ema-bg"),
                "indicator-ema-text": withAlpha("indicator-ema-text"),
                "indicator-ema-cross-bg": withAlpha("indicator-ema-cross-bg"),
                "indicator-ema-cross-text": withAlpha(
                    "indicator-ema-cross-text"
                ),
                "indicator-sma-bg": withAlpha("indicator-sma-bg"),
                "indicator-sma-text": withAlpha("indicator-sma-text"),
                "chart-selection-bg": withAlpha("chart-selection-bg"),
                "chart-selection-edge": withAlpha("chart-selection-edge"),
                "chart-selection-label-bg": withAlpha(
                    "chart-selection-label-bg"
                ),
                "chart-selection-handle-bg": withAlpha(
                    "chart-selection-handle-bg"
                ),
                "chart-selection-handle-hover": withAlpha(
                    "chart-selection-handle-hover"
                ),
                "chart-action-bg": withAlpha("chart-action-bg"),
                "chart-action-hover": withAlpha("chart-action-hover"),
                "toggle-on": withAlpha("toggle-on"),
                "toggle-off": withAlpha("toggle-off"),
                "toggle-knob": withAlpha("toggle-knob"),
                "timeframe-active": withAlpha("timeframe-active"),
                "leverage-low": withAlpha("leverage-low"),
                "leverage-mid": withAlpha("leverage-mid"),
                "leverage-high": withAlpha("leverage-high"),
                "leverage-critical": withAlpha("leverage-critical"),
                "leverage-max": withAlpha("leverage-max"),
                "loading-primary": withAlpha("loading-primary"),
                "loading-secondary": withAlpha("loading-secondary"),
                "loading-tertiary": withAlpha("loading-tertiary"),
            },
            boxShadow: {
                panel: "inset 0 1px 0 rgb(var(--glow-5) / 0.05)",
            },
        },
    },
};
