import {
    BookOpen,
    Boxes,
    Check,
    Clock3,
    Code2,
    Copy,
    Database,
    Gauge,
    ListChecks,
    LockKeyhole,
    Play,
    ScrollText,
    ShieldCheck,
    SquareFunction,
    Terminal,
    XCircle,
} from "lucide-react";
import { useState } from "react";
import type { ComponentType, ReactNode } from "react";
import readmeContent from "../../../README.md?raw";

type Section = {
    id: string;
    title: string;
    eyebrow: string;
    icon: ComponentType<{ className?: string }>;
};

const sections: Section[] = [
    {
        id: "lifecycle",
        title: "Lifecycle",
        eyebrow: "Which method runs",
        icon: Play,
    },
    {
        id: "common-variables",
        title: "Common Variables",
        eyebrow: "Available everywhere",
        icon: Boxes,
    },
    {
        id: "on-idle",
        title: "on_idle",
        eyebrow: "No position",
        icon: Clock3,
    },
    {
        id: "on-open",
        title: "on_open",
        eyebrow: "Position open",
        icon: LockKeyhole,
    },
    {
        id: "on-busy",
        title: "on_busy",
        eyebrow: "Order pending",
        icon: Gauge,
    },
    {
        id: "indicators",
        title: "Indicators",
        eyebrow: "extract()",
        icon: SquareFunction,
    },
    {
        id: "state",
        title: "State",
        eyebrow: "Persistent variables",
        icon: Database,
    },
    {
        id: "open-trades",
        title: "Open Trades",
        eyebrow: "Market and limit",
        icon: Terminal,
    },
    {
        id: "close-positions",
        title: "Close Positions",
        eyebrow: "Flatten and reduce",
        icon: XCircle,
    },
    {
        id: "timeouts-triggers",
        title: "Timeouts & Triggers",
        eyebrow: "TP, SL, TTL",
        icon: ShieldCheck,
    },
    {
        id: "examples",
        title: "Examples",
        eyebrow: "Working patterns",
        icon: Code2,
    },
    {
        id: "backtesting",
        title: "Backtesting",
        eyebrow: "Validate first",
        icon: ListChecks,
    },
    {
        id: "llm-prompt",
        title: "LLM Prompt",
        eyebrow: "Copy reference",
        icon: ScrollText,
    },
];

const sectionById = Object.fromEntries(
    sections.map((section) => [section.id, section])
) as Record<string, Section>;

const llmStrategyPrompt = `You are a strategy-generation assistant for KWANT, a Hyperliquid trading terminal where strategies are written as three Rhai scripts: on_idle, on_open, and on_busy.

The KWANT strategy API reference follows this prompt. Treat that reference as the source of truth. Use only variables, helpers, indicators, constants, object fields, and behavior documented there. Do not invent helper functions, indicators, order types, fields, imports, classes, async code, or external libraries.

When the user asks for a strategy:

1. If required details are missing, ask up to five concise clarifying questions. Required details usually include traded market, directional bias if any, timeframe, indicators/signals, risk sizing, exit behavior, and whether limit-order TTLs should FORCE or CANCEL. If the user asks you to decide, choose conservative defaults and state the assumptions.
2. Return a complete strategy package with these headings:
   - Strategy name
   - Intended market
   - Indicator configuration: list each asset, indicator, parameters, timeframe, and exact extract key
   - State declarations: a plain block suitable for the State Variables editor
   - on_idle: Rhai code block
   - on_open: Rhai code block
   - on_busy: Rhai code block
   - Behavior notes
   - Backtest checklist
3. Rhai code must compile under strict variables. Every referenced variable must be provided by the engine, declared as state, declared locally, or generated by an extract() statement.
4. Use extract() only in the supported source-transform shape:
   let name = extract("KEY");
   The key must be a string literal. After extraction, use generated names such as name_value, name_on_close, name_ts, name_short, name_long, name_trend, name_k, name_d, name_macd, name_signal, name_histogram, name_upper, name_mid, name_lower, or name_width according to indicator type.
5. Prefer self_ indicator keys for the traded market so the strategy is reusable across assets. Use explicit asset-prefixed keys for cross-asset filters.
6. Avoid repeated trades on the same candle. For candle-close logic, check name_on_close and usually store name_ts in state, then skip if it has already been processed.
7. In cross-asset strategies, do not assume last_price belongs to the traded market. Avoid deriving traded-market limit prices from last_price.close unless the strategy is intentionally single-asset or guarded by a self_ timestamp.
8. Use only documented order helpers. Market-vs-limit is chosen by helper name, not by a MAKER constant. FORCE TTL means cancel the target limit order, then submit the market equivalent. CANCEL TTL means cancel resting orders and defensively force-close if exposure exists.
9. If requested behavior cannot be represented with the documented API, say so clearly and provide the closest valid alternative.
10. Do not present generated strategies as financial advice or as profitable. Tell the user to backtest and inspect orders before live deployment.

Code style:
- Keep code blocks pure Rhai with no Markdown inside them.
- Use explicit returns when exiting early.
- Keep on_busy empty unless abort behavior is intentionally required.
- Use state names that are valid identifiers and do not collide with engine variables or constants.`;

const readmeReference = readmeContent.replace(
    /## LLM Strategy Generation Prompt[\s\S]*?---\n\n## Strategy Scripting API/,
    "## Strategy Scripting API"
);

const llmStrategyPromptBundle = `${llmStrategyPrompt}

---

KWANT STRATEGY API REFERENCE

${readmeReference}`;

const indicatorRows = [
    ["Single value", "RSI, EMA, DEMA, TEMA, SMA, ATR, ADX, ROC, OBV, CCI, Volume MA, Historical Volatility, VWAP Deviation, SMA on RSI", "name_value, name_on_close, name_ts"],
    ["EMA Cross", "{asset}_emaCross_{short}_{long}_{tf}", "name_short, name_long, name_trend, name_on_close, name_ts"],
    ["Stochastic RSI", "{asset}_stochRsi_{periods}_{k}_{d}_{tf}", "name_k, name_d, name_on_close, name_ts"],
    ["MACD", "{asset}_macd_{fast}_{slow}_{signal}_{tf}", "name_macd, name_signal, name_histogram, name_on_close, name_ts"],
    ["Ichimoku", "{asset}_ichimoku_{tenkan}_{kijun}_{senkou_b}_{tf}", "name_tenkan, name_kijun, name_span_a, name_span_b, name_chikou, name_on_close, name_ts"],
    ["Bollinger Bands", "{asset}_bollinger_{periods}_{std}_{tf}", "name_upper, name_mid, name_lower, name_width, name_on_close, name_ts"],
];

const timeframeRows = [
    ["1m", "MIN1"],
    ["3m", "MIN3"],
    ["5m", "MIN5"],
    ["15m", "MIN15"],
    ["30m", "MIN30"],
    ["1h", "HOUR1"],
    ["2h", "HOUR2"],
    ["4h", "HOUR4"],
    ["12h", "HOUR12"],
    ["1d", "DAY1"],
    ["3d", "indicator key only"],
    ["1w", "indicator key only"],
    ["1M", "indicator key only"],
];

function CodeBlock({ children }: { children: string }) {
    return (
        <pre className="border-line-subtle bg-app-surface-1/80 text-app-text/85 overflow-x-auto rounded-md border p-4 font-mono text-[12px] leading-relaxed">
            <code>{children}</code>
        </pre>
    );
}

function SectionHeader({
    id,
    eyebrow,
    title,
    icon: Icon,
}: {
    id: string;
    eyebrow: string;
    title: string;
    icon: ComponentType<{ className?: string }>;
}) {
    return (
        <div id={id} className="scroll-mt-24">
            <div className="mb-4 flex items-start gap-3">
                <div className="border-line-subtle bg-app-surface-2 text-accent-brand grid h-10 w-10 shrink-0 place-items-center rounded-md border">
                    <Icon className="h-5 w-5" />
                </div>
                <div>
                    <p className="text-app-text/40 text-xs font-medium uppercase">
                        {eyebrow}
                    </p>
                    <h2 className="text-app-text text-2xl font-semibold">
                        {title}
                    </h2>
                </div>
            </div>
        </div>
    );
}

function DocsSection({
    section,
    children,
}: {
    section: Section;
    children: ReactNode;
}) {
    return (
        <section className="border-line-subtle bg-surface-pane/80 rounded-md border p-5 md:p-6">
            <SectionHeader {...section} />
            <div className="space-y-5">{children}</div>
        </section>
    );
}

function InfoGrid({
    items,
}: {
    items: Array<{ title: string; body: string; code?: string }>;
}) {
    return (
        <div className="grid gap-3 md:grid-cols-3">
            {items.map((item) => (
                <div
                    key={item.title}
                    className="border-line-subtle bg-app-surface-2/70 rounded-md border p-4"
                >
                    <h3 className="text-app-text mb-2 text-sm font-semibold">
                        {item.title}
                    </h3>
                    <p className="text-app-text/60 text-sm leading-6">
                        {item.body}
                    </p>
                    {item.code && (
                        <p className="text-accent-brand-soft mt-3 font-mono text-xs">
                            {item.code}
                        </p>
                    )}
                </div>
            ))}
        </div>
    );
}

function DataTable({
    columns,
    rows,
}: {
    columns: string[];
    rows: string[][];
}) {
    return (
        <div className="overflow-hidden rounded-md border border-line-subtle">
            <table className="w-full text-left text-sm">
                <thead className="bg-app-surface-2 text-app-text/50">
                    <tr>
                        {columns.map((column) => (
                            <th key={column} className="px-4 py-3 font-medium">
                                {column}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody className="divide-line-subtle divide-y">
                    {rows.map((row) => (
                        <tr key={row.join("|")}>
                            {row.map((cell, index) => (
                                <td
                                    key={`${cell}-${index}`}
                                    className={
                                        index === 0
                                            ? "text-accent-brand-soft px-4 py-3 font-mono text-xs"
                                            : "text-app-text/65 px-4 py-3 text-sm leading-6"
                                    }
                                >
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}

export default function Docs() {
    const [copyStatus, setCopyStatus] = useState<
        "idle" | "copied" | "error"
    >("idle");

    const copyPromptBundle = async () => {
        try {
            await navigator.clipboard.writeText(llmStrategyPromptBundle);
            setCopyStatus("copied");
            window.setTimeout(() => setCopyStatus("idle"), 1800);
        } catch {
            setCopyStatus("error");
            window.setTimeout(() => setCopyStatus("idle"), 2400);
        }
    };

    return (
        <div className="bg-app-bg/50 min-h-screen px-4 py-6 pb-24 sm:px-6 lg:px-8">
            <div className="mx-auto grid max-w-[1500px] gap-6 lg:grid-cols-[260px_minmax(0,1fr)]">
                <aside className="lg:sticky lg:top-20 lg:h-[calc(100vh-6rem)] lg:self-start">
                    <nav className="border-line-subtle bg-surface-pane/85 rounded-md border p-3">
                        <div className="mb-3 flex items-center gap-2 px-2">
                            <BookOpen className="text-accent-brand h-4 w-4" />
                            <div>
                                <p className="text-app-text text-sm font-semibold">
                                    Strategy Docs
                                </p>
                                <p className="text-app-text/40 text-xs">
                                    Variables by method
                                </p>
                            </div>
                        </div>
                        <div className="space-y-1">
                            {sections.map((section) => (
                                <a
                                    key={section.id}
                                    href={`#${section.id}`}
                                    className="hover:bg-glow-5 text-app-text/70 hover:text-app-text flex items-center gap-2 rounded-md px-2 py-2 text-sm"
                                >
                                    <section.icon className="h-4 w-4 shrink-0" />
                                    <span>{section.title}</span>
                                </a>
                            ))}
                        </div>
                    </nav>
                </aside>

                <main className="space-y-6">
                    <header className="border-line-subtle bg-surface-pane/80 rounded-md border p-6">
                        <div className="mb-4 flex flex-wrap items-center gap-3">
                            <span className="border-accent-brand/40 bg-accent-brand/10 text-accent-brand-soft rounded-md border px-2.5 py-1 text-xs font-medium uppercase">
                                Rhai Strategy API
                            </span>
                            <span className="text-app-text/40 text-xs">
                                The clearest way to read this page: pick the
                                method you are writing, then use only the
                                variables listed for it.
                            </span>
                        </div>
                        <h1 className="text-app-text max-w-4xl text-3xl font-semibold leading-tight md:text-4xl">
                            Strategy scripts are three methods with explicit
                            variables.
                        </h1>
                        <p className="text-app-text/65 mt-4 max-w-4xl text-sm leading-7 md:text-base">
                            Every strategy has `on_idle`, `on_open`, and
                            `on_busy`. Each method receives the common runtime
                            variables, then one method-specific variable. The
                            script returns an intent such as `open_market`,
                            `flatten_limit`, `arm`, or nothing.
                        </p>
                    </header>

                    <DocsSection section={sectionById["lifecycle"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "on_idle",
                                    body: "Runs when the engine has no open position. It also runs while the strategy is armed.",
                                    code: "open, arm, disarm",
                                },
                                {
                                    title: "on_open",
                                    body: "Runs when the market already has an open position.",
                                    code: "flatten or reduce",
                                },
                                {
                                    title: "on_busy",
                                    body: "Runs while an open or close order is pending. Only abort() is acted on while busy.",
                                    code: "usually empty",
                                },
                            ]}
                        />
                        <CodeBlock>{`// Returning an intent tells the engine to act.
return open_market(LONG, margin_pct(50.0));

// Returning nothing means no trade for this tick.
return;

// A final expression also works.
open_market(LONG, margin_pct(50.0))

// A trailing semicolon turns the expression into (), so no intent is returned.
open_market(LONG, margin_pct(50.0));`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["common-variables"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            These names exist in all three methods:
                            `on_idle`, `on_open`, and `on_busy`.
                        </p>
                        <DataTable
                            columns={["Variable", "Type", "What it means"]}
                            rows={[
                                [
                                    "free_margin",
                                    "f64",
                                    "Available margin in USDC. Sizing helpers such as margin_pct() use this value.",
                                ],
                                [
                                    "lev",
                                    "i64",
                                    "Current leverage multiplier for the market.",
                                ],
                                [
                                    "last_price",
                                    "Price",
                                    "The candle that triggered this evaluation tick.",
                                ],
                                [
                                    "indicators",
                                    "Map",
                                    "Raw indicator map. Prefer extract() instead of accessing this directly.",
                                ],
                                [
                                    "state variables",
                                    "declared names",
                                    "Any variables declared in the State Variables box are available as bare names.",
                                ],
                            ]}
                        />
                        <DataTable
                            columns={["last_price field", "Type", "Meaning"]}
                            rows={[
                                ["last_price.open", "f64", "Candle open price."],
                                ["last_price.high", "f64", "Candle high price."],
                                ["last_price.low", "f64", "Candle low price."],
                                ["last_price.close", "f64", "Candle close price."],
                                ["last_price.vlm", "f64", "Candle volume."],
                                [
                                    "last_price.open_time",
                                    "i64",
                                    "Candle open timestamp in milliseconds.",
                                ],
                                [
                                    "last_price.close_time",
                                    "i64",
                                    "Candle close timestamp in milliseconds.",
                                ],
                            ]}
                        />
                        <div className="border-line-subtle bg-app-surface-2/70 rounded-md border p-4">
                            <p className="text-app-text/60 text-sm leading-6">
                                In a cross-asset strategy, `last_price` may be a
                                candle from a configured confirmation asset, not
                                the traded market. Use `self_` indicator keys
                                and timestamp guards when a calculation must be
                                tied to the traded market.
                            </p>
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["on-idle"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Use `on_idle` to look for entries or to manage the
                            armed state before an entry.
                        </p>
                        <DataTable
                            columns={["Variable", "Type", "What it means"]}
                            rows={[
                                [
                                    "is_armed",
                                    "i64",
                                    "Expiry timestamp in milliseconds while armed. It is -1 when not armed.",
                                ],
                            ]}
                        />
                        <CodeBlock>{`// on_idle
let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if is_armed > 0 && rsi_value < 30.0 {
    return open_market(LONG, margin_pct(50.0), sl_only(3.0));
}

if rsi_value < 35.0 {
    return arm(timedelta(MIN15, 1));
}`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["on-open"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Use `on_open` to manage an existing position. This
                            is where exits, partial closes, and position-side
                            checks belong.
                        </p>
                        <DataTable
                            columns={["Variable", "Type", "What it means"]}
                            rows={[
                                [
                                    "open_position",
                                    "OpenPosInfo",
                                    "The currently open position for the traded market.",
                                ],
                            ]}
                        />
                        <DataTable
                            columns={["open_position field", "Type", "Meaning"]}
                            rows={[
                                [
                                    "open_position.side",
                                    "Side",
                                    "LONG or SHORT. Compare directly with the constants.",
                                ],
                                [
                                    "open_position.size",
                                    "f64",
                                    "Current position size in asset units.",
                                ],
                                [
                                    "open_position.entry_px",
                                    "f64",
                                    "Average entry price.",
                                ],
                                [
                                    "open_position.open_time",
                                    "i64",
                                    "Position open timestamp in milliseconds.",
                                ],
                            ]}
                        />
                        <CodeBlock>{`// on_open
let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if open_position.side == LONG && rsi_value > 70.0 {
    return flatten_market();
}

if open_position.side == SHORT && rsi_value < 30.0 {
    return flatten_market();
}`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["on-busy"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Use `on_busy` only for emergency behavior. The
                            engine ignores returned trade intents while busy
                            unless the returned intent is `abort()`.
                        </p>
                        <DataTable
                            columns={["Variable", "Type", "What it means"]}
                            rows={[
                                [
                                    "busy_reason",
                                    "BusyType",
                                    "Whether the engine is waiting for an open or close order.",
                                ],
                            ]}
                        />
                        <DataTable
                            columns={["Helper", "Returns", "Meaning"]}
                            rows={[
                                [
                                    "busy_reason.is_opening()",
                                    "bool",
                                    "True while waiting for an open order to fill.",
                                ],
                                [
                                    "busy_reason.is_closing()",
                                    "bool",
                                    "True while waiting for a close order to fill.",
                                ],
                            ]}
                        />
                        <CodeBlock>{`// on_busy
// Most strategies should leave this empty.

// Emergency example:
if busy_reason.is_closing() {
    return abort();
}`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["indicators"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Add indicators in Lab, then click an indicator badge
                            to insert the exact `extract()` call. `extract()` is
                            a source transform, so it must use this exact shape:
                        </p>
                        <img
                            src="/add_indicator.png"
                            alt="Add indicator flow in strategy lab"
                            className="border-line-subtle mx-auto w-full max-w-xl rounded-md border object-contain"
                        />
                        <CodeBlock>{`let rsi = extract("self_rsi_14_15m");`}</CodeBlock>
                        <p className="text-app-text/65 text-sm leading-6">
                            The key must be a string literal and the statement
                            must end with a semicolon. If the indicator is
                            missing or still warming up, the generated code does
                            `return;` and skips the tick.
                        </p>
                        <DataTable
                            columns={["Indicator group", "Key format", "Generated variables"]}
                            rows={indicatorRows}
                        />
                        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
                            {timeframeRows.map(([suffix, constant]) => (
                                <div
                                    key={suffix}
                                    className="border-line-subtle bg-app-surface-2/70 flex items-center justify-between rounded-md border px-3 py-2 text-sm"
                                >
                                    <span className="text-accent-brand-soft font-mono">
                                        {suffix}
                                    </span>
                                    <span className="text-app-text/50 font-mono text-xs">
                                        {constant}
                                    </span>
                                </div>
                            ))}
                        </div>
                        <CodeBlock>{`// Use self_ for the traded market.
let market_rsi = extract("self_rsi_14_15m");

// Use explicit assets for confirmation signals.
let btc_rsi = extract("BTC_rsi_14_1h");

// Avoid repeated trades on the same closed candle.
if !market_rsi_on_close || market_rsi_ts == last_market_ts {
    return;
}

last_market_ts = market_rsi_ts;`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["state"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Declare state in Lab with one `name = default` per
                            line. State variables are loaded before each method
                            runs and written back after evaluation.
                        </p>
                        <CodeBlock>{`last_market_ts = 0
trade_count = 0
last_signal = "none"
prev_uptrend = null
can_trade = true`}</CodeBlock>
                        <InfoGrid
                            items={[
                                {
                                    title: "Default values",
                                    body: "Numbers, strings, booleans, and null are supported. null becomes Rhai ().",
                                },
                                {
                                    title: "Names",
                                    body: "Use identifiers that start with a letter or underscore, then letters, digits, or underscores.",
                                },
                                {
                                    title: "Shared methods",
                                    body: "The same state names are available in on_idle, on_open, and on_busy.",
                                },
                            ]}
                        />
                    </DocsSection>

                    <DocsSection section={sectionById["open-trades"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Open helpers are only useful from `on_idle`. Market
                            orders execute as taker orders. Limit orders place a
                            maker-style order at your limit price.
                        </p>
                        <CodeBlock>{`open_market(LONG, margin_pct(50.0), triggers(3.0, 2.0))

open_limit(
    LONG,
    margin_pct(40.0),
    last_price.close,
    timeout(CANCEL, timedelta(MIN15, 2)),
    triggers(3.0, 2.0),
)`}</CodeBlock>
                        <DataTable
                            columns={["Open helper", "Signature", "Meaning"]}
                            rows={[
                                [
                                    "open_market",
                                    "open_market(side, size)",
                                    "Open at market; optional TP/SL variant also exists.",
                                ],
                                [
                                    "open_market",
                                    "open_market(side, size, tp_sl)",
                                    "Attach triggers(tp, sl), tp_only(tp), or sl_only(sl).",
                                ],
                                [
                                    "open_limit",
                                    "open_limit(side, size, price)",
                                    "Place a limit open at the provided price.",
                                ],
                                [
                                    "open_limit",
                                    "open_limit(side, size, price, timeout)",
                                    "Add timeout(FORCE|CANCEL, timedelta(TF, count)).",
                                ],
                                [
                                    "open_limit",
                                    "open_limit(side, size, price, timeout, tp_sl)",
                                    "Use both timeout and TP/SL in one order intent.",
                                ],
                            ]}
                        />
                        <DataTable
                            columns={["Sizing helper", "Meaning", "Conversion"]}
                            rows={[
                                [
                                    "margin_pct(pct)",
                                    "Use a percentage of free margin.",
                                    "(free_margin * pct / 100 * lev) / reference_price",
                                ],
                                [
                                    "margin_amount(usdc)",
                                    "Use a fixed USDC margin amount.",
                                    "(amount * lev) / reference_price",
                                ],
                                [
                                    "raw_size(units)",
                                    "Use an exact asset-unit size.",
                                    "No margin conversion.",
                                ],
                            ]}
                        />
                    </DocsSection>

                    <DocsSection section={sectionById["close-positions"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Close helpers belong in `on_open`. `flatten_*`
                            closes the whole position. `reduce_*` closes part of
                            it.
                        </p>
                        <CodeBlock>{`flatten_market()
reduce_market(margin_pct(50.0))
flatten_limit(last_price.close, timeout(FORCE, timedelta(MIN5, 3)))
reduce_limit(
    margin_pct(50.0),
    last_price.close,
    timeout(CANCEL, timedelta(MIN15, 1)),
)`}</CodeBlock>
                        <DataTable
                            columns={["Close helper", "Signature", "Meaning"]}
                            rows={[
                                [
                                    "flatten_market",
                                    "flatten_market()",
                                    "Close the full open position at market.",
                                ],
                                [
                                    "flatten_limit",
                                    "flatten_limit(price)",
                                    "Close the full open position with a limit order.",
                                ],
                                [
                                    "flatten_limit",
                                    "flatten_limit(price, timeout)",
                                    "Full limit close with timeout policy.",
                                ],
                                [
                                    "reduce_market",
                                    "reduce_market(size)",
                                    "Partially close at market using the provided size.",
                                ],
                                [
                                    "reduce_limit",
                                    "reduce_limit(size, price)",
                                    "Partially close with a limit price.",
                                ],
                                [
                                    "reduce_limit",
                                    "reduce_limit(size, price, timeout)",
                                    "Partial limit close with timeout policy.",
                                ],
                            ]}
                        />
                    </DocsSection>

                    <DocsSection section={sectionById["timeouts-triggers"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "Triggers",
                                    body: "Attach take-profit and stop-loss to open orders with percentage values adjusted by leverage.",
                                    code: "triggers(5.0, 3.0)",
                                },
                                {
                                    title: "FORCE",
                                    body: "On timeout, cancel the target limit order and submit the market equivalent. Flatten force-closes at market.",
                                    code: "timeout(FORCE, timedelta(MIN15, 1))",
                                },
                                {
                                    title: "CANCEL",
                                    body: "On timeout, cancel tracked resting orders. If exposure exists after cancellation, the executor force-closes defensively.",
                                    code: "timeout(CANCEL, timedelta(MIN15, 1))",
                                },
                            ]}
                        />
                        <CodeBlock>{`triggers(5.0, 3.0)   // TP and SL
tp_only(5.0)          // TP only
sl_only(3.0)          // SL only

timeout(FORCE, timedelta(MIN15, 1))
timeout(CANCEL, timedelta(MIN15, 1))`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["examples"]}>
                        <div className="space-y-4">
                            <div>
                                <h3 className="text-app-text mb-2 text-base font-semibold">
                                    Minimal on_idle entry
                                </h3>
                                <CodeBlock>{`let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if rsi_value < 30.0 {
    return open_market(LONG, margin_pct(50.0), triggers(3.0, 2.0));
}`}</CodeBlock>
                            </div>
                            <div>
                                <h3 className="text-app-text mb-2 text-base font-semibold">
                                    Stateful one-trade-per-candle guard
                                </h3>
                                <CodeBlock>{`// State Variables
last_market_ts = 0

// on_idle
let ema = extract("self_emaCross_9_21_15m");

if !ema_on_close || ema_ts == last_market_ts {
    return;
}

last_market_ts = ema_ts;

if ema_trend {
    return open_market(LONG, margin_pct(40.0));
}`}</CodeBlock>
                            </div>
                            <div>
                                <h3 className="text-app-text mb-2 text-base font-semibold">
                                    on_open exit
                                </h3>
                                <CodeBlock>{`let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if open_position.side == LONG && rsi_value > 70.0 {
    return flatten_market();
}

if open_position.side == SHORT && rsi_value < 30.0 {
    return flatten_market();
}`}</CodeBlock>
                            </div>
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["backtesting"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "Before live use",
                                    body: "Backtest the strategy with the same scripts, state declarations, indicators, market, margin, leverage, fees, and funding assumptions.",
                                },
                                {
                                    title: "Why orders fail",
                                    body: "Common causes are compile errors, missing indicator warmup, min notional, invalid limit price, max size, or close-without-position.",
                                },
                                {
                                    title: "Sandbox limits",
                                    body: "Scripts are capped at 100,000 operations, expression depth 64, strings 4096 bytes, arrays 1024, and maps 256.",
                                },
                            ]}
                        />
                        <div className="border-line-subtle bg-app-surface-2/70 rounded-md border p-4">
                            <div className="mb-2 flex items-center gap-2">
                                <ShieldCheck className="text-accent-success h-4 w-4" />
                                <h3 className="text-app-text text-sm font-semibold">
                                    Minimum order value
                                </h3>
                            </div>
                            <p className="text-app-text/60 text-sm leading-6">
                                Open orders and partial closes must meet the
                                minimum notional of $10 USDC. Full closes may be
                                smaller.
                            </p>
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["llm-prompt"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Copy this into a new LLM chat before asking it to
                            write a strategy. The button copies both the system
                            prompt and the README strategy API reference.
                        </p>
                        <button
                            type="button"
                            onClick={copyPromptBundle}
                            className="border-accent-brand bg-accent-brand/15 text-accent-brand-soft hover:bg-accent-brand/25 flex w-full items-center justify-center gap-3 rounded-md border px-5 py-4 text-lg font-semibold tracking-wide sm:w-auto sm:min-w-72"
                        >
                            {copyStatus === "copied" ? (
                                <Check className="h-6 w-6" />
                            ) : (
                                <Copy className="h-6 w-6" />
                            )}
                            {copyStatus === "copied"
                                ? "COPIED"
                                : copyStatus === "error"
                                  ? "COPY FAILED"
                                  : "COPY"}
                        </button>
                        <CodeBlock>{llmStrategyPrompt}</CodeBlock>
                    </DocsSection>

                    <section className="border-line-subtle bg-app-surface-2/70 rounded-md border p-5">
                        <div className="flex items-start gap-3">
                            <ScrollText className="text-accent-brand mt-0.5 h-5 w-5" />
                            <div>
                                <h2 className="text-app-text text-base font-semibold">
                                    Source of truth
                                </h2>
                                <p className="text-app-text/60 mt-2 text-sm leading-6">
                                    Keep this page in sync with the Rust Rhai
                                    engine when variables, helper functions,
                                    indicator keys, or timeout behavior change.
                                </p>
                            </div>
                        </div>
                    </section>
                </main>
            </div>
        </div>
    );
}
