import {
    BookOpen,
    Braces,
    Check,
    Clock3,
    Code2,
    Compass,
    Copy,
    Database,
    Gauge,
    ImagePlus,
    ListChecks,
    Route,
    ScrollText,
    ShieldCheck,
    Terminal,
} from "lucide-react";
import { useState } from "react";
import type { ComponentType, ReactNode } from "react";
import readmeContent from "../../../README.md?raw";

type Section = {
    id: string;
    title: string;
    eyebrow: string;
    icon: ComponentType<{ className?: string }>;
};

const sections: Section[] = [
    {
        id: "overview",
        title: "Overview",
        eyebrow: "How scripts run",
        icon: Compass,
    },
    {
        id: "llm-prompt",
        title: "LLM Prompt",
        eyebrow: "Copy before asking",
        icon: ScrollText,
    },
    {
        id: "lifecycle",
        title: "Lifecycle",
        eyebrow: "Idle, open, busy",
        icon: Route,
    },
    {
        id: "authoring",
        title: "Authoring Rules",
        eyebrow: "Strict Rhai",
        icon: Code2,
    },
    {
        id: "orders",
        title: "Orders & TTL",
        eyebrow: "Intents",
        icon: Clock3,
    },
    {
        id: "indicators",
        title: "Indicators",
        eyebrow: "Keys and extract",
        icon: Gauge,
    },
    {
        id: "state",
        title: "State",
        eyebrow: "Persistent variables",
        icon: Database,
    },
    {
        id: "objects",
        title: "Runtime Objects",
        eyebrow: "Price, position, busy",
        icon: Braces,
    },
    {
        id: "examples",
        title: "Examples",
        eyebrow: "Patterns",
        icon: Terminal,
    },
    {
        id: "backtesting",
        title: "Backtesting",
        eyebrow: "Validation",
        icon: ListChecks,
    },
    {
        id: "screenshots",
        title: "Screenshot Slots",
        eyebrow: "Where images help",
        icon: ImagePlus,
    },
];

const sectionById = Object.fromEntries(
    sections.map((section) => [section.id, section])
) as Record<string, Section>;

const indicatorRows = [
    ["RSI", "{asset}_rsi_{periods}_{tf}", "rsi_value"],
    ["EMA", "{asset}_ema_{periods}_{tf}", "ema_value"],
    ["EMA Cross", "{asset}_emaCross_{short}_{long}_{tf}", "ema_short, ema_long, ema_trend"],
    ["Stochastic RSI", "{asset}_stochRsi_{periods}_{k}_{d}_{tf}", "stoch_k, stoch_d"],
    ["MACD", "{asset}_macd_{fast}_{slow}_{signal}_{tf}", "macd_macd, macd_signal, macd_histogram"],
    ["Ichimoku", "{asset}_ichimoku_{tenkan}_{kijun}_{senkou_b}_{tf}", "ichi_tenkan, ichi_kijun, ichi_span_a, ichi_span_b, ichi_chikou"],
    ["Bollinger Bands", "{asset}_bollinger_{periods}_{std}_{tf}", "bb_upper, bb_mid, bb_lower, bb_width"],
    ["ATR / ADX / SMA / DEMA / TEMA / ROC / OBV / Volume MA / Hist Vol / VWAP Dev / CCI", "Use the README key table", "{name}_value"],
];

const timeframeRows = [
    ["1m", "MIN1"],
    ["3m", "MIN3"],
    ["5m", "MIN5"],
    ["15m", "MIN15"],
    ["30m", "MIN30"],
    ["1h", "HOUR1"],
    ["2h", "HOUR2"],
    ["4h", "HOUR4"],
    ["12h", "HOUR12"],
    ["1d", "DAY1"],
    ["3d", "indicator key only"],
    ["1w", "indicator key only"],
    ["1M", "indicator key only"],
];

const llmStrategyPrompt = `You are a strategy-generation assistant for KWANT, a Hyperliquid trading terminal where strategies are written as three Rhai scripts: on_idle, on_open, and on_busy.

The KWANT strategy API reference follows this prompt. Treat that reference as the source of truth. Use only variables, helpers, indicators, constants, object fields, and behavior documented there. Do not invent helper functions, indicators, order types, fields, imports, classes, async code, or external libraries.

When the user asks for a strategy:

1. If required details are missing, ask up to five concise clarifying questions. Required details usually include traded market, directional bias if any, timeframe, indicators/signals, risk sizing, exit behavior, and whether limit-order TTLs should FORCE or CANCEL. If the user asks you to decide, choose conservative defaults and state the assumptions.
2. Return a complete strategy package with these headings:
   - Strategy name
   - Intended market
   - Indicator configuration: list each asset, indicator, parameters, timeframe, and exact extract key
   - State declarations: a plain block suitable for the State Variables editor
   - on_idle: Rhai code block
   - on_open: Rhai code block
   - on_busy: Rhai code block
   - Behavior notes
   - Backtest checklist
3. Rhai code must compile under strict variables. Every referenced variable must be provided by the engine, declared as state, declared locally, or generated by an extract() statement.
4. Use extract() only in the supported source-transform shape:
   let name = extract("KEY");
   The key must be a string literal. After extraction, use generated names such as name_value, name_on_close, name_ts, name_short, name_long, name_trend, name_k, name_d, name_macd, name_signal, name_histogram, name_upper, name_mid, name_lower, or name_width according to indicator type.
5. Prefer self_ indicator keys for the traded market so the strategy is reusable across assets. Use explicit asset-prefixed keys for cross-asset filters.
6. Avoid repeated trades on the same candle. For candle-close logic, check name_on_close and usually store name_ts in state, then skip if it has already been processed.
7. In cross-asset strategies, do not assume last_price belongs to the traded market. Avoid deriving traded-market limit prices from last_price.close unless the strategy is intentionally single-asset or guarded by a self_ timestamp.
8. Use only documented order helpers. Market-vs-limit is chosen by helper name, not by a MAKER constant. FORCE TTL means cancel the target limit order, then submit the market equivalent. CANCEL TTL means cancel resting orders and defensively force-close if exposure exists.
9. If requested behavior cannot be represented with the documented API, say so clearly and provide the closest valid alternative.
10. Do not present generated strategies as financial advice or as profitable. Tell the user to backtest and inspect orders before live deployment.

Code style:
- Keep code blocks pure Rhai with no Markdown inside them.
- Use explicit returns when exiting early.
- Keep on_busy empty unless abort behavior is intentionally required.
- Use state names that are valid identifiers and do not collide with engine variables or constants.`;

const readmeReference = readmeContent.replace(
    /## LLM Strategy Generation Prompt[\s\S]*?---\n\n## Strategy Scripting API/,
    "## Strategy Scripting API"
);

const llmStrategyPromptBundle = `${llmStrategyPrompt}

---

KWANT STRATEGY API REFERENCE

${readmeReference}`;

function CodeBlock({ children }: { children: string }) {
    return (
        <pre className="border-line-subtle bg-app-surface-1/80 text-app-text/85 overflow-x-auto rounded-md border p-4 font-mono text-[12px] leading-relaxed">
            <code>{children}</code>
        </pre>
    );
}

function SectionHeader({
    id,
    eyebrow,
    title,
    icon: Icon,
}: {
    id: string;
    eyebrow: string;
    title: string;
    icon: ComponentType<{ className?: string }>;
}) {
    return (
        <div id={id} className="scroll-mt-24">
            <div className="mb-4 flex items-start gap-3">
                <div className="border-line-subtle bg-app-surface-2 text-accent-brand grid h-10 w-10 shrink-0 place-items-center rounded-md border">
                    <Icon className="h-5 w-5" />
                </div>
                <div>
                    <p className="text-app-text/40 text-xs font-medium uppercase">
                        {eyebrow}
                    </p>
                    <h2 className="text-app-text text-2xl font-semibold">
                        {title}
                    </h2>
                </div>
            </div>
        </div>
    );
}

function InfoGrid({
    items,
}: {
    items: Array<{ title: string; body: string; code?: string }>;
}) {
    return (
        <div className="grid gap-3 md:grid-cols-3">
            {items.map((item) => (
                <div
                    key={item.title}
                    className="border-line-subtle bg-app-surface-2/70 rounded-md border p-4"
                >
                    <h3 className="text-app-text mb-2 text-sm font-semibold">
                        {item.title}
                    </h3>
                    <p className="text-app-text/60 text-sm leading-6">
                        {item.body}
                    </p>
                    {item.code && (
                        <p className="text-accent-brand-soft mt-3 font-mono text-xs">
                            {item.code}
                        </p>
                    )}
                </div>
            ))}
        </div>
    );
}

function ScreenshotSlot({
    title,
    description,
}: {
    title: string;
    description: string;
}) {
    return (
        <figure className="border-line-muted bg-app-surface-1/60 rounded-md border border-dashed p-5">
            <div className="mb-3 flex items-center gap-2">
                <ImagePlus className="text-accent-brand h-4 w-4" />
                <figcaption className="text-app-text text-sm font-semibold">
                    {title}
                </figcaption>
            </div>
            <p className="text-app-text/55 text-sm leading-6">
                {description}
            </p>
        </figure>
    );
}

function DocsSection({
    section,
    children,
}: {
    section: Section;
    children: ReactNode;
}) {
    return (
        <section className="border-line-subtle bg-surface-pane/80 rounded-md border p-5 md:p-6">
            <SectionHeader {...section} />
            <div className="space-y-5">{children}</div>
        </section>
    );
}

export default function Docs() {
    const [copyStatus, setCopyStatus] = useState<
        "idle" | "copied" | "error"
    >("idle");

    const copyPromptBundle = async () => {
        try {
            await navigator.clipboard.writeText(llmStrategyPromptBundle);
            setCopyStatus("copied");
            window.setTimeout(() => setCopyStatus("idle"), 1800);
        } catch {
            setCopyStatus("error");
            window.setTimeout(() => setCopyStatus("idle"), 2400);
        }
    };

    return (
        <div className="bg-app-bg/50 min-h-screen px-4 py-6 pb-24 sm:px-6 lg:px-8">
            <div className="mx-auto grid max-w-[1500px] gap-6 lg:grid-cols-[260px_minmax(0,1fr)]">
                <aside className="lg:sticky lg:top-20 lg:h-[calc(100vh-6rem)] lg:self-start">
                    <nav className="border-line-subtle bg-surface-pane/85 rounded-md border p-3">
                        <div className="mb-3 flex items-center gap-2 px-2">
                            <BookOpen className="text-accent-brand h-4 w-4" />
                            <div>
                                <p className="text-app-text text-sm font-semibold">
                                    Strategy Docs
                                </p>
                                <p className="text-app-text/40 text-xs">
                                    Rhai authoring guide
                                </p>
                            </div>
                        </div>
                        <div className="space-y-1">
                            {sections.map((section) => (
                                <a
                                    key={section.id}
                                    href={`#${section.id}`}
                                    className="hover:bg-glow-5 text-app-text/70 hover:text-app-text flex items-center gap-2 rounded-md px-2 py-2 text-sm"
                                >
                                    <section.icon className="h-4 w-4 shrink-0" />
                                    <span>{section.title}</span>
                                </a>
                            ))}
                        </div>
                    </nav>
                </aside>

                <main className="space-y-6">
                    <header className="border-line-subtle bg-surface-pane/80 rounded-md border p-6">
                        <div className="mb-4 flex flex-wrap items-center gap-3">
                            <span className="border-accent-brand/40 bg-accent-brand/10 text-accent-brand-soft rounded-md border px-2.5 py-1 text-xs font-medium uppercase">
                                Rhai Strategy API
                            </span>
                            <span className="text-app-text/40 text-xs">
                                Use this alongside the strategy editor in Lab.
                            </span>
                        </div>
                        <h1 className="text-app-text max-w-4xl text-3xl font-semibold leading-tight md:text-4xl">
                            Write, test, and deploy automated Hyperliquid
                            strategies.
                        </h1>
                        <p className="text-app-text/65 mt-4 max-w-4xl text-sm leading-7 md:text-base">
                            Strategies are three Rhai scripts compiled with
                            strict variables, evaluated by the Rust signal
                            engine, and translated into order intents. This page
                            turns the README into a practical authoring guide
                            with lifecycle rules, API references, and screenshot
                            slots for the UI.
                        </p>
                    </header>

                    <DocsSection section={sectionById["overview"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "Browser",
                                    body: "The Lab editor saves raw Rhai code, indicator config, and optional state declarations.",
                                },
                                {
                                    title: "Backend",
                                    body: "The backend expands macros, compiles strict ASTs, and stores the raw scripts in the database.",
                                },
                                {
                                    title: "Signal Engine",
                                    body: "Every relevant candle update refreshes indicators, evaluates one lifecycle script, and emits an optional intent.",
                                },
                            ]}
                        />
                        <CodeBlock>{`Browser editor -> save raw code
Backend -> expand extract() + state preamble -> compile AST
SignalEngine -> evaluate on_idle / on_open / on_busy
Executor -> place, cancel, or force orders on Hyperliquid`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["llm-prompt"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Copy this into a new LLM chat before asking it to
                            write a strategy. The button copies both the system
                            prompt and the README strategy API reference.
                        </p>
                        <button
                            type="button"
                            onClick={copyPromptBundle}
                            className="border-accent-brand bg-accent-brand/15 text-accent-brand-soft hover:bg-accent-brand/25 flex w-full items-center justify-center gap-3 rounded-md border px-5 py-4 text-lg font-semibold tracking-wide sm:w-auto sm:min-w-72"
                        >
                            {copyStatus === "copied" ? (
                                <Check className="h-6 w-6" />
                            ) : (
                                <Copy className="h-6 w-6" />
                            )}
                            {copyStatus === "copied"
                                ? "COPIED"
                                : copyStatus === "error"
                                  ? "COPY FAILED"
                                  : "COPY"}
                        </button>
                        <CodeBlock>{llmStrategyPrompt}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["lifecycle"]}>
                        <div className="overflow-hidden rounded-md border border-line-subtle">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-app-surface-2 text-app-text/50">
                                    <tr>
                                        <th className="px-4 py-3 font-medium">
                                            Script
                                        </th>
                                        <th className="px-4 py-3 font-medium">
                                            Runs When
                                        </th>
                                        <th className="px-4 py-3 font-medium">
                                            Extra Variable
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="divide-line-subtle divide-y">
                                    {[
                                        [
                                            "on_idle",
                                            "No position is open, or the strategy is armed.",
                                            "is_armed: expiry timestamp, or -1",
                                        ],
                                        [
                                            "on_open",
                                            "A position is open.",
                                            "open_position",
                                        ],
                                        [
                                            "on_busy",
                                            "An order is pending.",
                                            "busy_reason",
                                        ],
                                    ].map(([name, runs, extra]) => (
                                        <tr key={name}>
                                            <td className="text-accent-brand-soft px-4 py-3 font-mono">
                                                {name}
                                            </td>
                                            <td className="text-app-text/70 px-4 py-3">
                                                {runs}
                                            </td>
                                            <td className="text-app-text/60 px-4 py-3 font-mono text-xs">
                                                {extra}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        <p className="text-app-text/60 text-sm leading-6">
                            Each script may return an intent as its final
                            expression or with `return`. Returning `()` means no
                            trade for that tick.
                        </p>
                    </DocsSection>

                    <DocsSection section={sectionById["authoring"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "Strict variables",
                                    body: "Any referenced name must be declared by Rhai, the engine, state declarations, or extract expansion.",
                                    code: "typos fail on save",
                                },
                                {
                                    title: "Raw code is stored",
                                    body: "The DB keeps user code. Macro expansion is transient and happens before compile.",
                                    code: "extract() + state preamble",
                                },
                                {
                                    title: "Debugging",
                                    body: "Use print() in live mode. Runtime errors are sent to the market log and the tick emits no intent.",
                                    code: 'print("rsi=" + rsi_value)',
                                },
                            ]}
                        />
                        <CodeBlock>{`// Valid: final expression returns the intent
open_market(LONG, margin_pct(50.0))

// Valid: explicit return
return open_market(LONG, margin_pct(50.0));

// No trade: trailing semicolon makes the expression evaluate to ()
open_market(LONG, margin_pct(50.0));`}</CodeBlock>
                    </DocsSection>

                    <DocsSection section={sectionById["orders"]}>
                        <div className="grid gap-4 md:grid-cols-2">
                            <div className="space-y-3">
                                <h3 className="text-app-text text-base font-semibold">
                                    Open
                                </h3>
                                <CodeBlock>{`open_market(LONG, margin_pct(50.0))
open_market(SHORT, margin_amount(100.0), triggers(5.0, 3.0))
open_limit(LONG, raw_size(0.5), 42000.0)
open_limit(LONG, margin_pct(50.0), 42000.0, timeout(FORCE, timedelta(MIN15, 2)))`}</CodeBlock>
                            </div>
                            <div className="space-y-3">
                                <h3 className="text-app-text text-base font-semibold">
                                    Close
                                </h3>
                                <CodeBlock>{`flatten_market()
flatten_limit(43000.0, timeout(FORCE, timedelta(MIN5, 3)))
reduce_market(margin_pct(50.0))
reduce_limit(raw_size(0.1), 43000.0, timeout(CANCEL, timedelta(MIN15, 1)))`}</CodeBlock>
                            </div>
                        </div>
                        <InfoGrid
                            items={[
                                {
                                    title: "FORCE",
                                    body: "Cancels the target non-TP/SL limit order, then submits the market equivalent. Flatten force-close cancels tracked resting orders first.",
                                },
                                {
                                    title: "CANCEL",
                                    body: "Cancels tracked resting orders. If exposure exists after cancellation, the executor force-closes defensively.",
                                },
                                {
                                    title: "Validation",
                                    body: "Orders must pass min notional, max size, limit price, and TP/SL validation before submission.",
                                },
                            ]}
                        />
                    </DocsSection>

                    <DocsSection section={sectionById["indicators"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Indicator values are configured in the UI and read
                            with `extract()`. The traded market can also be
                            referenced with `self_...`, which makes reusable
                            strategies easier.
                        </p>
                        <CodeBlock>{`let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if rsi_value < 30.0 {
    return open_market(LONG, margin_pct(50.0));
}`}</CodeBlock>
                        <div className="overflow-hidden rounded-md border border-line-subtle">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-app-surface-2 text-app-text/50">
                                    <tr>
                                        <th className="px-4 py-3 font-medium">
                                            Indicator
                                        </th>
                                        <th className="px-4 py-3 font-medium">
                                            Key Format
                                        </th>
                                        <th className="px-4 py-3 font-medium">
                                            Variables
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="divide-line-subtle divide-y">
                                    {indicatorRows.map(([name, key, vars]) => (
                                        <tr key={name}>
                                            <td className="text-app-text/80 px-4 py-3">
                                                {name}
                                            </td>
                                            <td className="text-accent-brand-soft px-4 py-3 font-mono text-xs">
                                                {key}
                                            </td>
                                            <td className="text-app-text/60 px-4 py-3 font-mono text-xs">
                                                {vars}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
                            {timeframeRows.map(([suffix, constant]) => (
                                <div
                                    key={suffix}
                                    className="border-line-subtle bg-app-surface-2/70 flex items-center justify-between rounded-md border px-3 py-2 text-sm"
                                >
                                    <span className="text-accent-brand-soft font-mono">
                                        {suffix}
                                    </span>
                                    <span className="text-app-text/50 font-mono text-xs">
                                        {constant}
                                    </span>
                                </div>
                            ))}
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["state"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            State variables are declared in the editor, one per
                            line. They are loaded before each script evaluation
                            and written back after evaluation.
                        </p>
                        <CodeBlock>{`count = 0
last_signal = "none"
prev_uptrend = null
last_market_ts = 0`}</CodeBlock>
                        <CodeBlock>{`let rsi = extract("self_rsi_14_15m");

if !rsi_on_close || rsi_ts == last_market_ts {
    return;
}

last_market_ts = rsi_ts;
count += 1;`}</CodeBlock>
                        <InfoGrid
                            items={[
                                {
                                    title: "Supported defaults",
                                    body: 'Numbers, strings, booleans, and null. Null becomes Rhai ().',
                                },
                                {
                                    title: "Shared lifecycle",
                                    body: "The same state variables are visible in on_idle, on_open, and on_busy.",
                                },
                                {
                                    title: "Reset behavior",
                                    body: "State resets when the strategy reloads, the bot restarts, or a backtest engine resets.",
                                },
                            ]}
                        />
                    </DocsSection>

                    <DocsSection section={sectionById["objects"]}>
                        <div className="grid gap-4 md:grid-cols-3">
                            <div>
                                <h3 className="text-app-text mb-2 text-sm font-semibold">
                                    last_price
                                </h3>
                                <CodeBlock>{`.open
.high
.low
.close
.vlm
.open_time
.close_time`}</CodeBlock>
                            </div>
                            <div>
                                <h3 className="text-app-text mb-2 text-sm font-semibold">
                                    open_position
                                </h3>
                                <CodeBlock>{`.side
.size
.entry_px
.open_time`}</CodeBlock>
                            </div>
                            <div>
                                <h3 className="text-app-text mb-2 text-sm font-semibold">
                                    busy_reason
                                </h3>
                                <CodeBlock>{`busy_reason.is_opening()
busy_reason.is_closing()`}</CodeBlock>
                            </div>
                        </div>
                        <p className="text-app-text/60 text-sm leading-6">
                            Cross-asset strategies can evaluate on a non-market
                            asset tick, so derive limit prices from
                            `last_price.close` only when you know the tick
                            belongs to the traded market.
                        </p>
                    </DocsSection>

                    <DocsSection section={sectionById["examples"]}>
                        <div className="space-y-4">
                            <div>
                                <h3 className="text-app-text mb-2 text-base font-semibold">
                                    RSI mean reversion
                                </h3>
                                <CodeBlock>{`let rsi = extract("self_rsi_14_15m");

if !rsi_on_close {
    return;
}

if rsi_value < 30.0 {
    open_market(LONG, margin_pct(50.0), triggers(3.0, 2.0))
} else if rsi_value > 70.0 {
    open_market(SHORT, margin_pct(50.0), triggers(3.0, 2.0))
}`}</CodeBlock>
                            </div>
                            <div>
                                <h3 className="text-app-text mb-2 text-base font-semibold">
                                    Armed cross-asset entry
                                </h3>
                                <CodeBlock>{`let btc_rsi_1h = extract("BTC_rsi_12_1h");
let market_ema = extract("self_emaCross_9_21_15m");

if !market_ema_on_close || market_ema_ts == last_entry_ts {
    return;
}

last_entry_ts = market_ema_ts;

if is_armed > 0 && !prev_uptrend && market_ema_trend {
    prev_uptrend = market_ema_trend;
    return open_market(LONG, margin_pct(80.0), sl_only(28.0));
}

if btc_rsi_1h_value < 60.0 && !market_ema_trend {
    prev_uptrend = market_ema_trend;
    return arm(timedelta(MIN15, 1));
}

prev_uptrend = market_ema_trend;`}</CodeBlock>
                            </div>
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["backtesting"]}>
                        <InfoGrid
                            items={[
                                {
                                    title: "Inputs",
                                    body: "Choose strategy, traded asset, time range, resolution, margin, leverage, fees, and funding assumptions.",
                                },
                                {
                                    title: "Outputs",
                                    body: "Review equity curve, trade list, win rate, max drawdown, and position snapshots.",
                                },
                                {
                                    title: "Sandbox",
                                    body: "Scripts are capped at 100,000 operations, expression depth 64, strings 4096 bytes, arrays 1024, and maps 256.",
                                },
                            ]}
                        />
                        <div className="border-line-subtle bg-app-surface-2/70 rounded-md border p-4">
                            <div className="mb-2 flex items-center gap-2">
                                <ShieldCheck className="text-accent-success h-4 w-4" />
                                <h3 className="text-app-text text-sm font-semibold">
                                    Minimum order value
                                </h3>
                            </div>
                            <p className="text-app-text/60 text-sm leading-6">
                                Open orders and partial closes must meet the
                                minimum notional of $10 USDC. Full closes may be
                                smaller.
                            </p>
                        </div>
                    </DocsSection>

                    <DocsSection section={sectionById["screenshots"]}>
                        <p className="text-app-text/65 text-sm leading-6">
                            Add screenshots in these slots when you want the
                            docs to point directly at the current UI. Keep each
                            image focused on one workflow.
                        </p>
                        <div className="grid gap-4 md:grid-cols-2">
                            <ScreenshotSlot
                                title="Lab strategy editor"
                                description="Show the three script panels: on_idle, on_open, and on_busy. This is the best image near the Lifecycle section."
                            />
                            <ScreenshotSlot
                                title="State Variables box"
                                description="Show the one-per-line state initialization field. Use it near the State section."
                            />
                            <ScreenshotSlot
                                title="Add Indicator picker"
                                description="Show asset, indicator kind, parameters, timeframe, and the inserted extract() call. Use it near the Indicators section."
                            />
                            <ScreenshotSlot
                                title="Backtest run form and result"
                                description="Show the run configuration and the equity/trade result view. Use it near Backtesting."
                            />
                        </div>
                    </DocsSection>

                    <section className="border-line-subtle bg-app-surface-2/70 rounded-md border p-5">
                        <div className="flex items-start gap-3">
                            <ScrollText className="text-accent-brand mt-0.5 h-5 w-5" />
                            <div>
                                <h2 className="text-app-text text-base font-semibold">
                                    Source of truth
                                </h2>
                                <p className="text-app-text/60 mt-2 text-sm leading-6">
                                    This page is the readable in-app guide. Keep
                                    behavior details in sync with the root
                                    README and the Rust scripting engine when
                                    helper functions, indicators, or timeout
                                    behavior change.
                                </p>
                            </div>
                        </div>
                    </section>
                </main>
            </div>
        </div>
    );
}
